baseURL = "https://botaemeveryday.github.io/notes/"
locale = "ru-RU"
title = "botaemeveryday"

defaultContentLanguage = "ru"
hasCJKLanguage = true

[module]
  [module.hugoVersion]
  min = "0.97.0"
  extended = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      autoHeadingID = true
      [markup.goldmark.parser.attribute]
        title = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
  [markup.highlight]
    noClasses = false

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  author = "notakeith & salt-caramel"
  description = "botaemeveryday Конспектики"
  avatar = "https://avatars.githubusercontent.com/u/210124742"
  headerTitle = "botaemeveryday"
  motto = "Конспектики"
  favicon = "https://avatars.githubusercontent.com/u/210124742"
  stickyNav = false
  showTableOfContents = true
  showSummaryCoverInPost = true
  imageZoomableInPost = true
  showPrevNextPost = true
  coverStyle = 1

[outputs]
  home = ["HTML", "RSS", "JSON"]