baseURL = "http://notes.botaemeveryday.io/"
languageCode = 'ru-ru'
title = 'notakeith & salt-caramel'
theme = "dream"

defaultContentLanguage = "ru"
hasCJKLanguage = true  

[markup.goldmark.renderer]
  unsafe = true 

[params]
author = "notakeith & salt-caramel"
description = "botaemeveryday Конспектики"
avatar = "images/avatar.jpg"
headerTitle = "botaemeveryday"
motto = "Конспектики с любовью"
 
favicon = "favicon.ico"
 
stickyNav = false
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true
